### ISSUE TITLE
[idea] Simplify data/common.yaml leveraging yaml anchors for lookup_options

### ISSUE THREAD

**Issue by NITEMAN** [sbitio/puppet-ducktape#98]
A big bunch of lookup_options are WET.

Maybe we can rewrite the file using something like:
```yaml

deep_merge_w_ko: &DEEP_MERGE_WITH_KNOCKOUT
  merge:
    strategy: deep
    knockout_prefix: --KOP_

lookup_options:
  ducktape::apache::confs: *DEEP_MERGE_WITH_KNOCKOUT
  ducktape::apache::shield_vhost::port:
    merge: unique
  ducktape::archive::archives: *DEEP_MERGE_WITH_KNOCKOUT
...
```

/cc @jonhattan
